language: python
python:
  - "3.4"  # minimum supported version
  - "3.5"
  - "3.6"  # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - pip install -e .  # install dht into virtualenv for tests to import
  - pytest --cov=dht tests/